services:
  actual:
    image: actualbudget/actual-server:latest
    container_name: actual
    volumes:
      - ./actual-data:/data
    environment:
      - TZ=Asia/Ho_Chi_Minh
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:5006 >/dev/null 2>&1 || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
    networks:
      - homelab

networks:
  homelab:
    external: true
