version: '3.8'

services:
  # Dịch vụ Backend (API)
  backend:
    build:
      context: ./backend # Thư mục chứa Dockerfile của backend
    container_name: cv_backend
    environment:
      - PORT=${PORT}
    env_file:
      - .env
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules  # Exclude node_modules từ volume mapping
    networks:
      - cv-network

  # Dịch vụ Frontend (Giao diện người dùng)
  frontend:
    build:
      context: ./frontend # Thư mục chứa Dockerfile của frontend
    container_name: cv_frontend
    ports:
      - "81:80" # Ánh xạ port 81 của máy bạn vào port 80 của container (Nginx)
    depends_on:
      - backend # Frontend sẽ khởi động sau khi backend sẵn sàng
    volumes:
      - ./frontend/public:/usr/share/nginx/html
    networks:
      - cv-network

networks:
  cv-network:
    driver: bridge