version: '3'

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    environment:
      TZ: 'Asia/Ho_Chi_Minh'
      WEBPASSWORD: 'changeme123'  # Đổi mật khẩu tại đây
    volumes:
      - ./etc-pihole:/etc/pihole
      - ./etc-dnsmasq.d:/etc/dnsmasq.d
    ports:
      - "8053:53/tcp"
      - "8053:53/udp"
      - "8080:80/tcp"
    restart: unless-stopped
