services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: unless-stopped
    network_mode: "bridge"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8081:80/tcp"    # HTTP UI
      - "8443:443/tcp"   # HTTPS UI (mới thêm)
    environment:
      TZ: "${TZ}"
      WEBPASSWORD: "${PIHOLE_WEBPASSWORD}"
      DNSMASQ_LISTENING: "all"
    volumes:
      - ./etc-pihole:/etc/pihole
      - ./etc-dnsmasq.d:/etc/dnsmasq.d
