services:
  caddy:
    image: caddy:2
    container_name: caddy
    ports:
      - "127.0.0.1:8081:8080"     # <-- Tailscale Serve sẽ trỏ vào đây
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./conf.d:/etc/caddy/conf.d:ro
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped
    networks:
      - homelab

volumes:
  caddy_data:
  caddy_config:

networks:
  homelab:
    external: true
