services:
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      # Tailscale net only
      # - "80:80"
      # - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./data:/data
      - ./config:/config
      # Dòng quan trọng để tích hợp với Tailscale
      - /var/run/tailscale/tailscaled.sock:/var/run/tailscale/tailscaled.sock
    networks:
      - homelab

volumes:
  caddy_data:
  caddy_config:

networks:
  homelab:
    external: true
