version: "3"

services:
  portainer:
    image: portainer/portainer-ce
    ports:
      - "${PORTAINER_PORT}:9000"
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    env_file:
      - .env

  caddy:
    image: caddy:alpine
    ports:
      - "${CADDY_HTTP_PORT}:80"
      - "${CADDY_HTTPS_PORT}:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - portainer
    restart: unless-stopped
    env_file:
      - .env

volumes:
  portainer_data:
  caddy_data:
  caddy_config:
