services:
  portainer:
    image: portainer/portainer-ce:2.33.0-alpine
    ports:
      - "${PORTAINER_PORT}:9000"
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - homelab

volumes:
  portainer_data:

networks:
  homelab:
    external: true
